services:
  app_ash_promptql_mongo_2:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.ash_promptql_mongo_2
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_ASH_PROMPTQL_MONGO_2_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $APP_ASH_PROMPTQL_MONGO_2_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_ASH_PROMPTQL_MONGO_2_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_ASH_PROMPTQL_MONGO_2_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6064:8080
